services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html
      - ..:/workspace
    networks:
      - dev-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend.Dev
    ports:
      - "3000:80" # Serve the React build files using Apache on port 3000
    networks:
      - dev-network
    environment:
      - REACT_APP_API_URL=http://localhost:80

networks:
  dev-network:
    driver: bridge
