services:
  frontend:
    build:
      context: ../frontend/
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/usr/src/app
      - ..:/workspace
    working_dir: /usr/src/app
    networks:
      - app-network

  backend:
    build:
      context: ../backend/
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html
      - ..:/workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
