version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.Frontend.Dev
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 8081:8080
    working_dir: /var/www/html
    command: npm run serve
    networks:
      - webapp-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    volumes:
      - ./backend:/var/www/html
    ports:
      - 80:80
    depends_on:
      - frontend
    networks:
      - webapp-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

networks:
  webapp-network:
    driver: bridge
