version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "serve"]

  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
