FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Expose port 8080
EXPOSE 8080

# Start the app
CMD ["npm", "run", "serve"]
