# Dockerfile.Frontend.Dev
FROM node:18-alpine

# Set working directory
WORKDIR /var/www/html

# Install dependencies
COPY ./frontend/package*.json ./
RUN npm install

# Copy the rest of the frontend files
COPY ./frontend/ .

# Expose Vue app on port 8080
EXPOSE 8080

# Run the Vue dev server
CMD ["npm", "run", "serve"]
