version: '3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.Frontend.Dev
    volumes:
      - ../frontend:/workspace
    ports:
      - "8080:8080"
    command: npm run serve
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.Backend.Dev
    volumes:
      - ../backend:/var/www/html
    ports:
      - "80:80"
