services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend.Dev
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/html
      - ..:/workspace
    networks:
      - dev-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend.Dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/src/app
      - ..:/workspace
    networks:
      - dev-network
    environment:
      - VUE_APP_API_URL=http://localhost:80

networks:
  dev-network:
    driver: bridge
